[package]
name = "timezone-bot"
version = "0.1.0"
authors = ["jude-LafiteIII <judewrs@gmail.com>"]

[dependencies]
serenity = "0.5"
dotenv = "0.9.0"
typemap = "*"
mysql = "*"
chrono = "*"
chrono-tz = "*"
